"""Shared model registry and result-loading helpers for the dashboard."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict

from chest_xray_classifier.config.config import (
    CUSTOM_CNN_H5_PATH,
    EFFICIENTNETB0_H5_PATH,
    MOBILENETV2_H5_PATH,
    RESULTS_DIR,
)
from chest_xray_classifier.utils.model_loader import resolve_model_path


MODEL_REGISTRY: Dict[str, Dict] = {
    "Custom CNN": {
        "key": "custom_cnn",
        "path": Path(CUSTOM_CNN_H5_PATH),
        "description": "Baseline custom convolutional neural network",
    },
    "EfficientNetB0": {
        "key": "efficientnet",
        "path": Path(EFFICIENTNETB0_H5_PATH),
        "description": "Transfer learning model based on EfficientNetB0",
    },
    "MobileNetV2": {
        "key": "mobilenetv2",
        "path": Path(MOBILENETV2_H5_PATH),
        "description": "Lightweight transfer learning model based on MobileNetV2",
    },
}


COMPARISON_OUTPUT_DIR = Path(RESULTS_DIR) / "model_comparison"


def get_available_models() -> Dict[str, Path]:
    """Return all models whose saved weight files exist."""
    return {
        display_name: resolve_model_path(display_name) or info["path"]
        for display_name, info in MODEL_REGISTRY.items()
        if resolve_model_path(display_name) is not None
    }


def get_model_status_rows() -> list[dict]:
    """Return a small status table for the UI."""
    rows = []
    for display_name, info in MODEL_REGISTRY.items():
        rows.append({
            "Model": display_name,
            "Status": "Loaded" if resolve_model_path(display_name) else "Weights Missing",
            "Model File": (resolve_model_path(display_name) or info["path"]).name,
        })
    return rows


def get_model_key(display_name: str) -> str:
    """Get the stable internal key for a model display name."""
    return MODEL_REGISTRY[display_name]["key"]


def load_json_if_exists(path: Path):
    """Load JSON content from a file if it exists."""
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return None


def load_model_metrics(model_key: str):
    """Load per-model metrics generated by the comparison pipeline."""
    candidate_paths = [
        COMPARISON_OUTPUT_DIR / f"{model_key}_dashboard_metrics.json",
        COMPARISON_OUTPUT_DIR / f"{model_key}_metrics_summary.json",
        Path(RESULTS_DIR) / "comparison" / f"{model_key}_metrics_summary.json",
    ]
    for path in candidate_paths:
        data = load_json_if_exists(path)
        if data is not None:
            return data
    return None


def load_comparison_table():
    """Load the overall comparison CSV if it exists."""
    comparison_csv = COMPARISON_OUTPUT_DIR / "comparison_table.csv"
    if comparison_csv.exists():
        import pandas as pd

        return pd.read_csv(comparison_csv)
    fallback = COMPARISON_OUTPUT_DIR / "model_comparison.csv"
    if fallback.exists():
        import pandas as pd

        return pd.read_csv(fallback)
    return None
