"""
PDF Report Generator component.
Generates highly polished clinical diagnostic reports in PDF format using fpdf2.
Supports both single patient scans and batch diagnostic summaries.
"""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from fpdf import FPDF

class MedicalPDFReport(FPDF):
    def header(self):
        # Top banner styling (deep medical navy color theme)
        self.set_fill_color(15, 23, 42) # Slate-900
        self.rect(0, 0, 210, 38, 'F')
        
        self.set_text_color(255, 255, 255)
        self.set_font("helvetica", "B", 16)
        self.set_y(10)
        self.cell(0, 10, "CHEST X-RAY DIAGNOSTIC CLINICAL REPORT", align="C", ln=True)
        self.set_font("helvetica", "I", 9)
        self.cell(0, 4, "Automated Computer Vision Decision-Support System Summary", align="C", ln=True)
        self.ln(12)

    def footer(self):
        self.set_y(-25)
        self.set_font("helvetica", "I", 8)
        self.set_text_color(148, 163, 184) # slate-400
        
        # Medical disclaimer callout box in footer
        self.set_fill_color(248, 250, 252) # Slate-50
        self.rect(10, 270, 190, 16, 'F')
        self.set_y(-20)
        self.cell(0, 4, "CLINICAL WARNING: This automated prediction report is generated by a computer vision model for research purposes only.", align="C", ln=True)
        self.cell(0, 4, "It is NOT a medical diagnosis and should never replace professional clinical interpretation by a licensed radiologist.", align="C", ln=True)
        
        self.set_draw_color(226, 232, 240)
        self.line(10, 287, 200, 287)
        self.set_y(-7)
        self.cell(0, 5, f"Page {self.page_no()}", align="C")

def generate_clinical_pdf(
    image_path: str | Path,
    gradcam_path: str | Path | None,
    prediction: str,
    confidence: float,
    uncertainty: float,
    model_name: str,
    inference_ms: float,
    threshold: float
) -> bytes:
    """Compile and return binary PDF bytes for a single patient diagnostic report."""
    pdf = MedicalPDFReport()
    pdf.add_page()
    
    # 1. Report Metadata
    pdf.set_y(44)
    pdf.set_text_color(15, 23, 42) # Slate-900
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 6, "1. REPORT METADATA & SYSTEM DETAILS", ln=True)
    pdf.set_draw_color(226, 232, 240) # Slate-200
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    
    pdf.set_font("helvetica", "", 9.5)
    pdf.cell(95, 5, f"Date generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S local')}")
    pdf.cell(95, 5, f"AI Model Configuration: {model_name}", ln=True)
    pdf.cell(95, 5, f"Inference Latency: {inference_ms:.1f} ms")
    pdf.cell(95, 5, f"Decision threshold set: {threshold:.0%}", ln=True)
    pdf.ln(4)
    
    # 2. Executive Summary
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 6, "2. CLINICAL EXECUTIVE SUMMARY", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(3)
    
    # Callout box for classification results
    pdf.set_fill_color(241, 245, 249) # slate-100
    pdf.rect(10, pdf.get_y(), 190, 24, 'F')
    
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(190, 7, f"    PREDICTED PRIMARY DIAGNOSIS: {prediction.upper()}", ln=True)
    pdf.set_font("helvetica", "", 10)
    pdf.cell(95, 6, f"    Model Confidence Score: {confidence:.2%}")
    pdf.cell(95, 6, f"Predictive Uncertainty (Entropy): {uncertainty:.2%}", ln=True)
    
    status_label = "NOMINAL (Review standard protocol)"
    if confidence < threshold:
        status_label = "ATTENTION REQUIRED (Uncertainty threshold warning)"
    pdf.cell(190, 6, f"    Diagnostic status check: {status_label}", ln=True)
    pdf.ln(8)
    
    # 3. Visual Attributions
    pdf.set_font("helvetica", "B", 11)
    pdf.cell(0, 6, "3. INTERPRETABILITY & ATTRIBUTION MAPS (GRAD-CAM)", ln=True)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(4)
    
    img_y = pdf.get_y()
    img_p = str(Path(image_path).resolve())
    
    if gradcam_path and Path(gradcam_path).exists():
        gcam_p = str(Path(gradcam_path).resolve())
        # Draw side-by-side
        pdf.image(img_p, x=15, y=img_y, w=80, h=80)
        pdf.image(gcam_p, x=115, y=img_y, w=80, h=80)
        
        pdf.set_y(img_y + 81)
        pdf.set_font("helvetica", "I", 8.5)
        pdf.set_text_color(100, 116, 139) # slate-500
        pdf.cell(95, 4, "Figure A: Original Patient Scan", align="C")
        pdf.cell(95, 4, "Figure B: Grad-CAM Feature Attributions", align="C", ln=True)
    else:
        # Draw single centered image
        pdf.image(img_p, x=65, y=img_y, w=80, h=80)
        pdf.set_y(img_y + 81)
        pdf.set_font("helvetica", "I", 8.5)
        pdf.set_text_color(100, 116, 139)
        pdf.cell(0, 4, "Figure A: Original Patient Scan (Attributions Disabled)", align="C", ln=True)
        
    pdf.ln(6)
    pdf.set_text_color(15, 23, 42)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 5, "Heatmap Interpretation:", ln=True)
    pdf.set_font("helvetica", "", 9.5)
    pdf.multi_cell(0, 5.2, "The saliency heatmap illustrates pixel-level attributions contributing to the final Softmax prediction. Bright highlighted regions (red/yellow) indicate where the model detected patterns resembling focal consolidations (pneumonia) or ground-glass opacities (COVID). This visualization is intended only to explain model behavior and does not represent medically confirmed pathology.")
    
    # 4. Recommendations
    pdf.ln(4)
    pdf.set_font("helvetica", "B", 10)
    pdf.cell(0, 5, "Clinical Recommendations:", ln=True)
    pdf.set_font("helvetica", "", 9.5)
    if confidence < threshold:
        pdf.multi_cell(0, 5.2, "1. Warning: Prediction confidence is below the configured clinical threshold. Prompt radiologist review is strongly advised.\n2. Cross-correlate model findings with patient temperature, WBC count, and clinical auscultation findings.\n3. Request high-resolution CT scan if ground-glass opacity pattern remains highly suspected.")
    else:
        pdf.multi_cell(0, 5.2, "1. Diagnostic confidence is within acceptable limits. Complete standard clinical file logging.\n2. Correlate with clinical history and patient symptoms before final diagnosis discharge.")
        
    return bytes(pdf.output())

def generate_batch_pdf(
    results_list: list[dict],
    model_name: str,
    threshold: float
) -> bytes:
    """Compile and return binary PDF bytes for a batch diagnostics summary report."""
    pdf = MedicalPDFReport()
    pdf.add_page()
    
    # Title
    pdf.set_y(44)
    pdf.set_text_color(15, 23, 42)
    pdf.set_font("helvetica", "B", 12)
    pdf.cell(0, 6, "BATCH DIAGNOSTIC SUMMARY RUN", ln=True)
    pdf.set_draw_color(226, 232, 240)
    pdf.line(10, pdf.get_y(), 200, pdf.get_y())
    pdf.ln(2)
    
    pdf.set_font("helvetica", "", 9.5)
    pdf.cell(95, 5, f"Date generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S local')}")
    pdf.cell(95, 5, f"AI Model Configuration: {model_name}", ln=True)
    pdf.cell(95, 5, f"Total Files Processed: {len(results_list)}")
    pdf.cell(95, 5, f"Confidence threshold: {threshold:.0%}", ln=True)
    pdf.ln(6)
    
    # Render table of results
    pdf.set_font("helvetica", "B", 10)
    # Draw headers
    pdf.set_fill_color(241, 245, 249)
    pdf.cell(55, 7, "Filename", border=1, fill=True)
    pdf.cell(45, 7, "Predicted Disease", border=1, fill=True)
    pdf.cell(30, 7, "Confidence", border=1, fill=True)
    pdf.cell(30, 7, "Uncertainty", border=1, fill=True)
    pdf.cell(30, 7, "Review Status", border=1, fill=True, ln=True)
    
    pdf.set_font("helvetica", "", 9)
    for res in results_list:
        status_text = "OK"
        if res["confidence"] < threshold:
            status_text = "REVIEW"
            
        pdf.cell(55, 7, f" {res['filename'][:25]}", border=1)
        pdf.cell(45, 7, f" {res['prediction']}", border=1)
        pdf.cell(30, 7, f" {res['confidence']:.1%}", border=1)
        pdf.cell(30, 7, f" {res['uncertainty']:.1%}", border=1)
        
        # Color code review status cell
        if status_text == "REVIEW":
            pdf.set_text_color(239, 68, 68) # Red
            pdf.cell(30, 7, f" {status_text}", border=1, ln=True)
            pdf.set_text_color(15, 23, 42)
        else:
            pdf.set_text_color(34, 197, 94) # Green
            pdf.cell(30, 7, f" {status_text}", border=1, ln=True)
            pdf.set_text_color(15, 23, 42)
            
    # Add page for each individual result
    for idx, res in enumerate(results_list):
        pdf.add_page()
        pdf.set_y(44)
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(0, 6, f"INDIVIDUAL FILE ANALYSIS: {res['filename']}", ln=True)
        pdf.line(10, pdf.get_y(), 200, pdf.get_y())
        pdf.ln(3)
        
        # Details Box
        pdf.set_fill_color(241, 245, 249)
        pdf.rect(10, pdf.get_y(), 190, 20, 'F')
        
        pdf.set_font("helvetica", "B", 11)
        pdf.cell(190, 6.5, f"    PREDICTED PRIMARY DIAGNOSIS: {res['prediction'].upper()}", ln=True)
        pdf.set_font("helvetica", "", 9.5)
        pdf.cell(95, 6, f"    Model Confidence Score: {res['confidence']:.2%}")
        pdf.cell(95, 6, f"Predictive Uncertainty (Entropy): {res['uncertainty']:.2%}", ln=True)
        pdf.ln(10)
        
        # Embed original image
        img_y = pdf.get_y()
        project_root = Path(__file__).resolve().parents[3]
        img_p = str(project_root / "outputs" / f"diag_{res['filename']}")
        
        try:
            if Path(img_p).exists():
                pdf.image(img_p, x=65, y=img_y, w=80, h=80)
                pdf.set_y(img_y + 81)
                pdf.set_font("helvetica", "I", 8.5)
                pdf.set_text_color(100, 116, 139)
                pdf.cell(0, 4, "Figure: Patient Chest X-Ray Scan", align="C", ln=True)
        except Exception as exc:
            pdf.set_font("helvetica", "I", 9)
            pdf.cell(0, 10, f"Error rendering image: {exc}", ln=True)
            
        pdf.ln(6)
        pdf.set_text_color(15, 23, 42)
        pdf.set_font("helvetica", "B", 10)
        pdf.cell(0, 5, "Clinical Recommendations:", ln=True)
        pdf.set_font("helvetica", "", 9.5)
        if res["confidence"] < threshold:
            pdf.multi_cell(0, 5.2, "1. Warning: Prediction confidence is below the configured threshold. Radiologist review is strongly advised.\n2. Correlate with clinical diagnostic lab records.")
        else:
            pdf.multi_cell(0, 5.2, "1. Confidence score is nominal. Proceed with standard chart logging protocol.")
            
    return bytes(pdf.output())
